version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flask_api_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  mage:
    image: mageai/mageai:latest
    container_name: mage
    restart: always
    ports:
      - "6789:6789"
    volumes:
      - ./mage_data:/home/src

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  celery_worker:
    build: .
    container_name: celery_worker
    restart: always
    depends_on:
      - rabbitmq
      - redis
    environment:
      CELERY_BROKER_URL: "pyamqp://guest:guest@rabbitmq:5672//"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    command: celery -A tasks worker --loglevel=info

  consumer:
    build: .
    container_name: rabbitmq_consumer
    restart: always
    depends_on:
      - rabbitmq
    command: python tasks.py  # Run the message consumer

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  celery_beat:
    build: .
    container_name: celery_beat
    restart: always
    depends_on:
      - redis
      - rabbitmq
    command: celery -A tasks beat --loglevel=info


volumes:
  pg_data:
  mage_data:
